<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Server.Web</RootNamespace>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Radzen.Blazor" Version="11.2.8" />
    <PackageReference Include="BCnEncoder.Net" Version="2.3.0" />
    <PackageReference Include="SkiaSharp" Version="4.151.1" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="4.151.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\LibraryCore\LibraryCore.csproj" />
    <ProjectReference Include="..\ServerLibrary\ServerLibrary.csproj" />
    <ProjectReference Include="..\Plugin.Abstractions\Plugin.Abstractions.csproj" />
  </ItemGroup>
</Project>
